package game.d6shooters.game;

public enum SquadState {
    REGULAR, REROLL1, REROLL2, ALLOCATE, OTHER, CHECKHEAT, GUNFIGHT, MOVE, TOWN, ENDGAME, NEXTTURN, CROSSROAD,
    EVENT, EVENT2, EVENT3, EVENT6,
    POKER1, POKER2, POKER3, POKER4,
}
